### ISSUE TITLE
Remove need for PHP & composer on host

### ISSUE THREAD

**Issue by robertlemke** [flownative/localbeach#28]
In GitLab by @kdambekalns on Jul 11, 2019, 12:28

Following the instructions here: https://www.flownative.com/en/documentation/guides/beach/local-beach-setup-docker-based-neos-development-howto.html

But I get: "Could not find Flow or Neos installation in your current path!"

You need to run composer install first, then it will work. But what is the use of running it dockerized if I need to install php locally first?

**Comment by robertlemke** [comment]
Solved by providing the Go client.

**Comment by kdambekalns** [comment]
Well, the need for composer still exists, even if that's bearable with our Docker images…
